### ISSUE TITLE
Task #2

### ISSUE THREAD

**Issue by ala-n** [AnastasiaHarost/instagram_project#2]
[-] Filters behavior unclear, fields for filtering date & author are missed
[-] (9-10) tag field behaviour is unclear, too
[-] Incorrect password state
[-] Show more behavior not described.

[+] 0.5) Like the flow of interactions you drawed. The main "scenario" is clear from wireframes.

Please make an updates, it's easy and will not take much time and you will have a very nice mark on practice )
Current mark: 6

**Comment by AnastasiaHarost** [comment]
new version is ready

**Comment by ala-n** [comment]
Cool! Going to review it one more time tomorrow. From the quick view all super nice now ;)
Thanks!
