### ISSUE TITLE
Task #3

### ISSUE THREAD

**Issue by ala-n** [AnastasiaHarost/instagram_project#4]
HTML
[=] (cosmetic) `<button type="submit" name="" value="" class="submit"></button>`
name, value attrs for button is redundant.
[-] (cleancode) `<form action="javascript:alert('hi')" method="post" class="search">`
 class 'search' doesn't say much. better search-form or smth like that.
[-] `<div class="user"><b>user1</b></div>` try to not use `<b>` outside of preformatted text,
u have CSS font-weight to make something bolder.
[-] `<div class="sub">` again class name didn't say much.
[=] `<div class="active-btn-container">
            <a href="#" class="add-btn">add post</a>
        </div>`
active-btn-container,  why active ? :)
[-] (critical) duplicated id's (post structure)
[=] moving  div.show-more-posts outside of .phototape will save your time in the future.

[-] (semantic) 
`<a href="/search/cats/">#cats</a><a href="/search/kitten/">#kitten</a>
                        <a href="/search/beauty/">#beauty</a><a href="/search/kittenlife/">#kittenlife</a>`
semantically it's list so better 
```
<ul class="tag-list">
<li><a href="/search/cats/" class="tag">#cats</a></li>
<li><a href="/search/kitten/" class="tag">#kitten</a></li>
<li><a href="/search/beauty/" class="tag">#beauty</a></li>
<li><a href="/search/kittenlife/" class="tag">#kittenlife</a></li>
</ul>
```
'+ proper CSS styling

[+] time tag, nice!

CSS
[-] inline-flexbox -> inline-flex
[-] responsiveness (media queries commented)
[+] generally likes what happens in css

Current mark is 7+

**Comment by AnastasiaHarost** [comment]
New version is ready, check, please)

**Comment by ala-n** [comment]
[-] (minor) `<img src = "images/1.jpg" alt = "cat" width= "100%" >` width should be in CSS, but big '+' for alt attribute.
Looks very nice semantically. And you've big collection of '+', so minor "-" was totally covered )
You have **10** now.
Thanks!
